export const UPDATE_LISTS = "UPDATE_LISTS";
export const REMOVE_LIST = "REMOVE_LIST";
export const SET_CURRENT_LIST = "SET_CURRENT_LIST";
export const ADD_LIST = "ADD_LIST";
export const LOADING = "LOADING";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
